### ISSUE TITLE
I have import error 

### ISSUE THREAD

**Issue by prathapsagar** [Seeed-Studio/Seeed_Python_MLX9064x#1]
I have error when I try to import the package in kine 694 I2C can somebody please help me solve this please any suggestions

**Comment by Pillar1989** [comment]
Do you use raspberry pi?

**Comment by prathapsagar** [comment]
> Do you use raspberry pi?

Yes I am using raspberry pi 3b+

**Comment by Pillar1989** [comment]
Can you describe your problem in detail? All my tests are normal.

**Comment by prathapsagar** [comment]
> Can you describe your problem in detail? All my tests are normal.

See I installed the python module using sudo pip3 install but when I try to import seeed_mlx90640 I get a error saying there’s an ‘error in line 694 ‘ If you have any example with output can you please post it

**Comment by Pillar1989** [comment]
https://github.com/Seeed-Studio/Seeed_Python_MLX90640/blob/master/README.md
You need to follow the readme documentation. Using only PIP is not acceptable.

**Comment by prathapsagar** [comment]
> https://github.com/Seeed-Studio/Seeed_Python_MLX90640/blob/master/README.md
> You need to follow the readme documentation. Using only PIP is not acceptable.

So I should also use the curl line to get grove pi drive ??

**Comment by Pillar1989** [comment]
Yes
