### ISSUE TITLE
MLX9060 I2C lib issue: AttributeError: 'SMBus' object has no attribute 'msg'

### ISSUE THREAD

**Issue by impeer** [Seeed-Studio/Seeed_Python_MLX9064x#2]
Hey,

I am having trouble with your MLX9060 I2C lib

I installed grove.py, followed tutorial :

https://pypi.org/project/seeed-python-mlx90640/#description

And everything goes fine up to the moment when I try to initialize the sensor:

>
import seeed_mlx90640
mlx = seeed_mlx90640.grove_mxl90640()

What I get is :

pi@raspberrypi:~ $ python3 infrared.py     ## just a script name with copy&paste of the above two lines
Traceback (most recent call last):
  File "infrared.py", line 2, in <module>
    mlx = seeed_mlx90640.grove_mxl90640()
  File "/home/pi/.local/lib/python3.7/site-packages/seeed_mlx90640.py", line 58, in __init__
    self.refresh_rate = RefreshRate.REFRESH_0_5_HZ 
  File "/home/pi/.local/lib/python3.7/site-packages/seeed_mlx90640.py", line 83, in refresh_rate
    self._I2CReadWords(0x800D, controlRegister)
  File "/home/pi/.local/lib/python3.7/site-packages/seeed_mlx90640.py", line 699, in _I2CReadWords
    write = self.bus.msg.write(self.addr,[addr>>8,addr&0xFF])
  File "/home/pi/.local/lib/python3.7/site-packages/grove/i2c.py", line 51, in __getattr__
    return getattr(self.instance, name)
AttributeError: 'SMBus' object has no attribute 'msg'

I'm at loss and google gives me nothing. I can see the software is young. Any hints?

Thank you

**Comment by Hansen0314** [comment]
you can use https://github.com/Seeed-Studio/grove.py#install-grovepy to update the newest Grove.py to resolve this problem.

**Comment by impeer** [comment]
Aright, so I did it again. I did:

`pi@raspberrypi:~/2 $ git clone https://github.com/Seeed-Studio/grove.py
Cloning into 'grove.py'...
remote: Enumerating objects: 5, done.
remote: Counting objects: 100% (5/5), done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 1265 (delta 0), reused 2 (delta 0), pack-reused 1260
Receiving objects: 100% (1265/1265), 636.12 KiB | 1.20 MiB/s, done.
Resolving deltas: 100% (828/828), done.


pi@raspberrypi:~/2 $ cd grove.py/
pi@raspberrypi:~/2/grove.py $ sudo pip install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/2/grove.py
Requirement already satisfied: RPi.GPIO in /usr/lib/python2.7/dist-packages (from grove.py==0.6) (0.7.0)
Requirement already satisfied: rpi_ws281x in /usr/local/lib/python2.7/dist-packages (from grove.py==0.6) (4.2.3)
Requirement already satisfied: smbus2 in /usr/local/lib/python2.7/dist-packages (from grove.py==0.6) (0.3.0)
Building wheels for collected packages: grove.py
  Running setup.py bdist_wheel for grove.py ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-7jy7Mp/wheels/75/e9/7c/4e8984224bddd70b038a8d79d539c117533a9b707de39bc770
Successfully built grove.py
Installing collected packages: grove.py
  Found existing installation: grove.py 0.6
    Uninstalling grove.py-0.6:
      Successfully uninstalled grove.py-0.6
Successfully installed grove.py-0.6

pi@raspberrypi:~/2/grove.py $ sudo pip3 install .
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Processing /home/pi/2/grove.py
Requirement already satisfied: RPi.GPIO in /usr/lib/python3/dist-packages (from grove.py==0.6) (0.7.0)
Requirement already satisfied: rpi_ws281x in /usr/local/lib/python3.7/dist-packages (from grove.py==0.6) (4.2.3)
Requirement already satisfied: smbus2 in /usr/local/lib/python3.7/dist-packages (from grove.py==0.6) (0.3.0)
Building wheels for collected packages: grove.py
  Running setup.py bdist_wheel for grove.py ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-eyjkh07x/wheels/75/e9/7c/4e8984224bddd70b038a8d79d539c117533a9b707de39bc770
Successfully built grove.py
Installing collected packages: grove.py
  Found existing installation: grove.py 0.6
    Uninstalling grove.py-0.6:
      Successfully uninstalled grove.py-0.6
Successfully installed grove.py-0.6
`
Python version

`pi@raspberrypi:~/grove.py $ python -V
Python 3.7.3
`

I tried 
`curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -
`

But it does something like 

`curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -

Warning: apt-key output should not be parsed (stdout is not a terminal)
Hit:1 http://archive.raspberrypi.org/debian buster InRelease                   
Hit:2 http://raspbian.raspberrypi.org/raspbian buster InRelease                
Hit:3 https://seeed-studio.github.io/pi_repo stretch InRelease                 
Reading package lists... Done                             
Building dependency tree       
Reading state information... Done
268 packages can be upgraded. Run 'apt list --upgradable' to see them.
I2C interface enabled...
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-rpi.gpio is already the newest version (0.7.0~buster-1).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-rpi.gpio is already the newest version (0.7.0~buster-1).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libmraa1 is already the newest version (1.9.0-git20191021-pi20191021).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-mraa is already the newest version (1.9.0-git20191021-pi20191021).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python-upm is already the newest version (1.6.0-git20191021-pi20191021).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-mraa is already the newest version (1.9.0-git20191021-pi20191021).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
python3-upm is already the newest version (1.6.0-git20191021-pi20191021).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libbma456 is already the newest version (1.0.0-1).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Reading package lists... Done
Building dependency tree       
Reading state information... Done
libbmi088 is already the newest version (0.0.2-1).
0 upgraded, 0 newly installed, 0 to remove and 268 not upgraded.
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rpi-ws281x in /usr/local/lib/python2.7/dist-packages (4.2.3)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rpi-ws281x in /usr/local/lib/python3.7/dist-packages (4.2.3)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: smbus in /usr/local/lib/python2.7/dist-packages (1.1.post2)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: smbus in /usr/local/lib/python3.7/dist-packages (1.1.post2)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: smbus2 in /usr/local/lib/python2.7/dist-packages (0.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: smbus2 in /usr/local/lib/python3.7/dist-packages (0.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: bme680 in /usr/local/lib/python2.7/dist-packages (1.0.5)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: bme680 in /usr/local/lib/python3.7/dist-packages (1.0.5)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rpi-vl53l0x in /usr/local/lib/python2.7/dist-packages (0.0.3)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: rpi-vl53l0x in /usr/local/lib/python3.7/dist-packages (0.0.3)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: sgp30 in /usr/local/lib/python2.7/dist-packages (0.1.6)
Requirement already satisfied: smbus2 in /usr/local/lib/python2.7/dist-packages (from sgp30) (0.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: sgp30 in /usr/local/lib/python3.7/dist-packages (0.1.6)
Requirement already satisfied: smbus2 in /usr/local/lib/python3.7/dist-packages (from sgp30) (0.3.0)
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting https://github.com/Seeed-Studio/grove.py/archive/master.zip
  Cache entry deserialization failed, entry ignored
  Downloading https://github.com/Seeed-Studio/grove.py/archive/master.zip
     | 1.3MB 1.9MB/s^Z
[1]+  Stopped                 curl -sL https://github.com/Seeed-Studio/grove.py/raw/master/install.sh | sudo bash -s -
`

And freezes forever so I had to kill it, like, three times I tried. I understood that installing through pip3 should be equivalent. Also, just pip3 install should be enough and i did pip & pip3 but only because standalone pip3 install threw same errors so I just tried something else.

Some sample from grove.py lib 
`import time
from grove.gpio import GPIO

led = GPIO(12, GPIO.OUT)
button = GPIO(22, GPIO.IN)

`

Throws no errors. Just initializing the mlx class.

**Comment by Hansen0314** [comment]
It is very helpful for you to update the library by using `sudo pip --force-reinstall .` since the pip' mechanism.

**Comment by arituerto** [comment]
Hello,

I'm receiving the same error running from a virtual environment:
```bash
File "/home/pi/volvis_sam_integration/venv/lib/python3.7/site-packages/seeed_mlx90640.py", line 58, in __init__
    self.refresh_rate = RefreshRate.REFRESH_0_5_HZ 
  File "/home/pi/volvis_sam_integration/venv/lib/python3.7/site-packages/seeed_mlx90640.py", line 83, in refresh_rate
    self._I2CReadWords(0x800D, controlRegister)
  File "/home/pi/volvis_sam_integration/venv/lib/python3.7/site-packages/seeed_mlx90640.py", line 699, in _I2CReadWords
    write = self.bus.msg.write(self.addr,[addr>>8,addr&0xFF])
  File "/home/pi/volvis_sam_integration/venv/lib/python3.7/site-packages/grove/i2c.py", line 51, in __getattr__
    return getattr(self.instance, name)
AttributeError: 'SMBus' object has no attribute 'msg'
```
```bash
python --version
Python 3.7.3
```
```bash
pip list
Package               Version  
--------------------- ---------
grove.py              0.6      
numpy                 1.18.2   
opencv-contrib-python 3.4.4.19 
opencv-python         3.4.4.19 
picamera              1.13     
pip                   20.0.2   
pyFirmata             1.1.0    
pyserial              3.4      
rpi-ws281x            4.2.3    
RPi.GPIO              0.7.0    
seeed-python-mlx90640 1.1.0    
setuptools            46.1.3   
smbus                 1.1.post2
smbus2                0.3.0    
wheel                 0.34.2 
```

I followed the Readme.md instructions to install `grove.py`. What am I missing?

Thanks in advance

**Comment by Hansen0314** [comment]
do you use `sudo pip --force-reinstall .` to install.

**Comment by arituerto** [comment]
I cloned grovy repo and reinstalled it. Now it seems to work. Anyway I will try that.

Thanks!
