### ISSUE TITLE
Why do i get value > 300 with function "getFrame" ?

### ISSUE THREAD

**Issue by jerOnGHub** [Seeed-Studio/Seeed_Python_MLX9064x#4]
Hi, I recently use your library to get data from the MLX90640.
When i get data with the function "getFrame" which say in description "...and calculate the temperature in C for each of 32x24 pixels...".
datasheet of MLX90640 say it can measure temperature from -40 to 300°C, so do you have any clue why i get lots of value > 300 ?

Thanks in advance for your reply,
Jerevi.

**Comment by Hansen0314** [comment]
Hi there:
   1. It is very helpful for you to modify the parameter at the https://github.com/Seeed-Studio/Seeed_Python_MLX90640/blob/2679628592fea137775ba6e0d070fbceb821ed6f/seeed_mlx90640.py#L91 to resolve your problem. 
 2.can you give me a frame data that you got?
 3.you can get more information about the parameter by accessing the [datasheet](https://files.seeedstudio.com/wiki/IR-thermal-imaging-sensor-MLX90640-/MLX90640-Datasheet-Melexis.pdf)

**Comment by Pillar1989** [comment]
@jerevi  Does this issues need more discussion?
