### ISSUE TITLE
Not working anymore with 90640

### ISSUE THREAD

**Issue by albydnc** [Seeed-Studio/Seeed_Python_MLX9064x#5]
Python gives me this error
```
    self.mlx = seeed_mlx9064x.grove_mxl90640()
  File "/usr/local/lib/python3.7/dist-packages/seeed_mlx9064x.py", line 86, in __init__
    super(grove_mxl90641, self).__init__(address)
TypeError: super(type, obj): obj must be an instance or subtype of type
```

**Comment by Hansen0314** [comment]
Hi @albydnc :
  thanks for your feedback. we have been fixed this error.

**Comment by anim070** [comment]
Python give me this error --
Traceback (most recent call last):
  File "Scripts/test_seeed_mlx90640.py", line 22, in <module>
    main()
  File "Scripts/test_seeed_mlx90640.py", line 9, in main
    mlx = seeed_mlx9064x.grove_mxl90640()
  File "/home/pi/.virtualenvs/tg_seeed/lib/python3.7/site-packages/seeed_mlx9064x.py", line 86, in __init__
    super(grove_mxl90641, self).__init__(address)
TypeError: super(type, obj): obj must be an instance or subtype of type
My virtual env details ---
grove.py              0.6
pip                   20.1.1
pyserial              3.4
rpi-ws281x            4.2.4
RPi.GPIO              0.7.0
Seeed-grove.py        0.3
seeed-python-mlx90640 1.1.0
seeed-python-mlx9064x 1.1.3
setuptools            49.1.0
smbus2                0.3.0
spidev                3.5
wheel                 0.34.2

**Comment by Hansen0314** [comment]
Hi @anim070 :
1.git pull to get the newest source code.
2.`cd Seeed_Python_MLX9064x` and `sudo pip3 install --force-reinstall .` to install the newest lib.
