### ISSUE TITLE
getFrame(self, framebuff) has "nan" strings!

### ISSUE THREAD

**Issue by lamba92** [Seeed-Studio/Seeed_Python_MLX9064x#6]
In code highlighted [here](https://github.com/Seeed-Studio/Seeed_Python_MLX9064x/blob/master/seeed_mlx9064x.py#L116-L130) the `framebuff` array gets filled with some `nan`s string values. Why so? Is it expected or a bug?

**Comment by lamba92** [comment]
After few tries now the entire array is made of `nan`. Also I amy be using the `mxl90641` model, not entirely sure since this other [issue](https://forum.seeedstudio.com/t/thermal-camera-mlx90641-raspberry-pi-4-grove-base-hat-problem/252963)!

**Comment by is-qian** [comment]
Currently, there is no update on this aspect. You can try modifying GrovePi to run it. If you get good results, you can submit a pull request to us for testing.

**Comment by is-qian** [comment]
I just tested using the MLX90641 and did not encounter such a phenomenon. Regarding the other issue you mentioned, you can refer to #8 for modifications to your code. If you continue to face this problem, feel free to reopen this issue and ask further questions.
